name: test_m_bagasi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  double_back_to_close_app: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  photo_view: ^0.15.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mock_data/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
